AI/urls.py
from django.urls import path
from .views import DiseaseDetectionCreationView, DetectionInformation, ListDetectionsForUser, ListDetectionModels

app_name = 'AI'

urlpatterns = [
    path('create', DiseaseDetectionCreationView.as_view(), name='create'),
    path('info', DetectionInformation.as_view()),
    path('list', ListDetectionsForUser.as_view()),
    path('models', ListDetectionModels.as_view(), name='models')
]

Auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/', include('account.urls')),
    path('detection/',include('AI.urls')),
    path('', include('website.urls')),
]

website/urls.py
from django.urls import path
from .views import LoginView, HomeView, DetectionView, SignupView, AboutView

app_name = "website"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(),name='register'),
    path('', HomeView.as_view(), name='home'),
    path('detection/', DetectionView.as_view(),name='detection'),
    path('about/', AboutView.as_view(), name='about'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated

class LoginView(APIView):
    def get(self, request, format=None):
        return render(request, 'user/signin.html')

class SignupView(APIView):
    def get(self, request, format=None):
        return render(request, 'user/signup.html')
    

class HomeView(APIView): 
    def get(self, request, format=None):
        return render(request,'website/index.html')
    
class DetectionView(APIView):
    def get(self, request, format=None):
        return render(request,'website/detection.html')

class AboutView(APIView):
    def get(self, request, format=None):
        return render(request,'website/about.html')

website/templates/website/about.html
{% extends 'base.html' %}
{% block title %}
  About
{% endblock %}
{% block header %}
  <link rel="stylesheet" href="/static/css/aboutStyle.css" />
{% endblock %}

{% block body %}
  <body><div style="background-color: gray; color: black;">
    <br /><p align="center">About the Website:</p><br />
  </div><br />
<p style="text-align: center;">Developed during the month of July, 2023. The website implements various Technologies including: Machine Learning (TensorFlow, Keras), Django framework, Web Development, Languages including: Pythonl, HTML, CSS, JavaScript</p>
  <br />
    <div style="background-color: gray; color: black;">
      <br /><p align="center">About the creators:</p><br />
    </div><br />
    <div class="grid">
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?lion" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Ali Haider Khan</h2>
            </div>
            <p class="card-text">
              Student, 4th Year, B.Tech. CSE <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">LinkedIn</a> <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">GitHub</a>
            </p>
          </div>
        </div>
      </div>
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?cheetah" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Tanveer Singh</h2>
            </div>
            <p class="card-text">
              Student, 4th Year, B.Tech. CSE <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">LinkedIn</a> <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">GitHub</a>
            </p>
          </div>
        </div>
      </div>
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?tiger" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Ratnakar Sharma</h2>
            </div>
            <p class="card-text">
              Student, 4th Year, B.Tech. CSE <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">LinkedIn</a> <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">GitHub</a>
            </p>
          </div>
        </div>
      </div>
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?bird" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Navneet Kaur</h2>
            </div>
            <p class="card-text">
              Student, 4th Year, B.Tech. CSE <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">LinkedIn</a> <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">GitHub</a>
            </p>
          </div>
        </div>
      </div>
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?kid" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Tashu Bansal</h2>
            </div>
            <p class="card-text">
              Student, 4th Year, B.Tech. CSE <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">LinkedIn</a> <br /><br />
              <a href="" target="_blank" style="color: white; text-decoration: underline; font-size: small;">GitHub</a>
            </p>
          </div>
        </div>
      </div>
    </div>
    <br /><br />
  </body>
{% endblock %}

website/templates/website/detection.html
{% extends 'base.html' %}
{% block title %}
Detect
{% endblock %}
{% block header %}
<link rel="stylesheet" href="/static/css/detectionStyles.css" />
<script>
  const createUrl = "{% url 'AI:create' %}";
  const modelsUrl = "{% url 'AI:models' %}";
</script>
{% endblock %}

{% block body %}

<body>
  <div style="background-color: gray;">
    <br />
    <p align="center" style="color: black;">
      Welcome to CropDiseaseAI <br />
      Here with our highly accurate predicting models, you can get to know whether your crop is healthy or has any kind
      of disease.
    </p>
    <br />
  </div>
  <div class="sidebyside">
    <div class="grid-item">
      <div class="card">
        <div class="card-content">
          <div class="card-content">
            <h2 class="card-header" style="font-size: large;">Choose your Crop</h2>
          </div>
          <p class="card-text">
            <select class="dropdown" style="font-size: large;" id="crops-dropdown" onload="loadModels()">

            </select>
          </p>
        </div>
      </div>
    </div>
    <div class="container">
      <h3>Upload your file</h3>
      <div class="drag-area">
        <div class="icon">
          <i class="fas fa-images"></i>
        </div>
        <span class="header">Drag & Drop</span>
        <span class="header">or <span class="button">Browse</span></span>
        <input id="inputImage" type="file" hidden />
        <span class="support">Supports: JPEG, PNG, JPG</span>
      </div>
    </div>
    <div class="grid-item">
      <div class="newthing">
        <div class="newthing-text">
          <h2 style="font-size: xx-large;" id="diseaseHolder"></h2>
        </div>
      </div>
      <div class="newthing">
        <div class="newthing-text">
          <h2 style="font-size: large;">Tip:</h2>
          <p style="font-size: small;">Tip to avoid the disease here</p>
        </div>
      </div>
    </div>
  </div>
  <div class="submit">
    <a class="cta" href="#"><button style="color: white; background-color: rgba(227, 3, 3, 0.997); margin-right: 20px;"
        class="navi reset-button">Reset</button></a>
    <a class="cta" href="#"><button onclick="createImage(event)" style="color: white;">Submit</button></a>
  </div>
  <script src="/static/js/detectionScript.js"></script>
</body>
{% endblock %}

website/templates/website/index.html
{% extends 'base.html' %}
{% block title %}
  Home
{% endblock %}
{% block header %}
  <link rel="stylesheet" href="/static/css/indexStyle.css" />
{% endblock %}

{% block body %}
  <body>
    <div style="background-color: gray; color: black;">
      <br /><p align="center">
        Welcome to CropDiseaseDetector<br />Trending topics and Latest news regarding Crops
      </p><br />
    </div><br /><br />
    <div class="grid">
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?potato" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Potatoes</h2>
            </div>
            <p class="card-text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus, tempore suscipit voluptas soluta repudiandae reprehenderit ut autem corrupti consectetur rerum quae quaerat optio dolores quod blanditiis, eligendi at nam eveniet. hello all, good evening, testing going on at 11:41 am.</p>
          </div>
        </div>
      </div>
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?Apple" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Apples</h2>
            </div>
            <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit eligendi obcaecati odio, veritatis dicta sequi velit ipsa suscipit ea vitae, sed fuga rerum, officia est necessitatibus? Ab repudiandae magni qui.</p>
          </div>
        </div>
      </div>
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?oranges" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Oranges</h2>
            </div>
            <p class="card-text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus, tempore suscipit voluptas soluta repudiandae reprehenderit ut autem corrupti consectetur rerum quae quaerat optio dolores quod blanditiis, eligendi at nam eveniet.</p>
          </div>
        </div>
      </div>
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?carrot" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Oranges</h2>
            </div>
            <p class="card-text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus, tempore suscipit voluptas soluta repudiandae reprehenderit ut autem corrupti consectetur rerum quae quaerat optio dolores quod blanditiis, eligendi at nam eveniet.</p>
          </div>
        </div>
      </div>
      <div class="grid-item">
        <div class="card">
          <img class="card-img" src="https://source.unsplash.com/200x200/?veggies" alt="Potatoesssss" />
          <div class="card-content">
            <div class="card-content">
              <h2 class="card-header">Oranges</h2>
            </div>
            <p class="card-text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus, tempore suscipit voluptas soluta repudiandae reprehenderit ut autem corrupti consectetur rerum quae quaerat optio dolores quod blanditiis, eligendi at nam eveniet.</p>
          </div>
        </div>
      </div>
    </div>
    <br /><br />
    <footer class="footer">
      <div class="footer-content">
        <div class="footer-column" style="margin-left: 100px;">
          <ul>
            <li>
              Contact info: <a href="emailto:1035alihaider@gmail.com">1035alihaider@gmail.com</a>
            </li>
            <li>
              Link to other pages: <a href="about.html">About</a>, <a href="detection.html">Detect PlantDiseaseAI</a>
            </li>
          </ul>
        </div>
        <div class="footer-column" style="margin-right: 100px;">
          <ul>
            <li>
              Contact info: <a href="emailto:1035alihaider@gmail.com">1035alihaider@gmail.com</a>
            </li>
            <li>
              Link to other pages: <a href="about.html">About</a>, <a href="detection.html">Detect PlantDiseaseAI</a>
            </li>
          </ul>
        </div>
      </div>
      <br />
      <p>&copy; 2023 CropDiseaseDetector. All rights reserved.</p>
    </footer>
  </body>
{% endblock %}