AI/urls.py
from django.urls import path
from .views import DiseaseDetectionCreationView, DetectionInformation, ListDetectionsForUser, ListDetectionModels

app_name = 'AI'

urlpatterns = [
    path('create', DiseaseDetectionCreationView.as_view(), name='create'),
    path('info', DetectionInformation.as_view()),
    path('list', ListDetectionsForUser.as_view()),
    path('models', ListDetectionModels.as_view(), name='models')
]

Auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/', include('account.urls')),
    path('detection/',include('AI.urls')),
    path('', include('website.urls')),
]

account/urls.py
from .views import UserRegisterationForm, UserLoginForm, UserProfileView, UserChangePasswordView, SendPasswordResetEmailView, UserPasswordResetView
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView

app_name = 'account'

urlpatterns = [
    path('register/', UserRegisterationForm.as_view(), name='register'),
    path('signin/', UserLoginForm.as_view(), name='signin'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('changepassword/', UserChangePasswordView.as_view(), name='changepassword'),
    path('forgotpassword/',SendPasswordResetEmailView.as_view(), name='forgotpassword' ),
    path('forgotpassword/<uid>/<token>', UserPasswordResetView.as_view()),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

website/urls.py
from django.urls import path
from .views import LoginView, HomeView, DetectionView, SignupView, AboutView

app_name = "website"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(),name='register'),
    path('', HomeView.as_view(), name='home'),
    path('detection/', DetectionView.as_view(),name='detection'),
    path('about/', AboutView.as_view(), name='about'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated

class LoginView(APIView):
    def get(self, request, format=None):
        return render(request, 'user/signin.html')

class SignupView(APIView):
    def get(self, request, format=None):
        return render(request, 'user/signup.html')
    

class HomeView(APIView): 
    def get(self, request, format=None):
        return render(request,'website/index.html')
    
class DetectionView(APIView):
    def get(self, request, format=None):
        return render(request,'website/detection.html')

class AboutView(APIView):
    def get(self, request, format=None):
        return render(request,'website/about.html')

website/templates/user/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %}login{% endblock title %} | zAppDjango</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <script>
        const loginEndpoint = 'http://127.0.0.1/api/user/signin/'
        const Login = async (event) => {
          event.preventDefault()
        
          const email = document.getElementById('inputEmail').value
          const password = document.getElementById('inputPassword').value

          const csrf = document.getElementsByName('csrfmiddlewaretoken')[0].value

          const formData = JSON.stringify({"email": email, "password": password, "csrfmiddlewaretoken" : csrf});
          let newImage = await fetch(loginEndpoint,  {
            headers: {"content-type": "application/json"},
            method: 'POST',
            body: formData
          }).then(response => response.json())
          .then(data =>{
            console.log(data);
            const { sucess } = data;
            if(!sucess){
                console.log({"Errors":data})
            }
            else{
                const { tokens } = data
                const { access } = tokens
                const { refresh } = tokens

                localStorage.setItem('access_token', access)
                localStorage.setItem('refresh_token', refresh)
                
                console.log("Access")
                console.log(access)
                console.log("Refresh")
                console.log(refresh)
                //if(access && refresh){
                //    window.location.href = "{% url 'website:home' %}"
                //}
            }
          })
          .catch(error => { console.error(error) })
      
        }
      
      </script>

    <form class="form-signin" method="post" action="/login">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Username</label>
        <input type="text" id="inputEmail" name="username" class="form-control" placeholder="Username" required
            autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button onclick="Login(event)">Login</button>
        
    </form>

</body>

</html>

website/templates/user/signin.html
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <title>Login | PlantDiseaseDetector</title>
    <link rel="stylesheet" href="/static/css/style.css" />
    <script>const post_url = "{% url 'account:signin' %}";
            const home_url = "{% url 'website:home' %}"
    </script>
    <script type="text/javascript"  src="/static/js/saveJWT.js"></script>
  </head>

  <body>
    <div class="wrapper">
      <div class="title">Login</div>
      <form id="submit-form">
        {% csrf_token %}
        <div class="field">
          <input name="email" type="text" required />
          <label>Email Address</label>
        </div>
        <div class="field">
          <input  name="password" type="password" required />
          <label>Password</label>
        </div>
        <div class="content">
          <div class="checkbox">
            <input type="checkbox" id="remember-me" />
            <label for="remember-me">Remember me</label>
          </div>
          <div class="pass-link">
            <a href="#">Forgot password?</a>
          </div>
        </div>
        <div class="field">
          <input type="button"  onclick="Submit(event)" value="Login" />
        </div> 
        <div class="signup-link">
          Not a member? <a href= "{% url 'website:register' %}">Signup now</a>
        </div>
      </form>
    </div>
  </body>
</html>

website/templates/user/signup.html
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <title>Sign Up Form | PlantDiseaseDetector</title>
    <link rel="stylesheet" href="/static/css/style.css" />
    <script>const post_url = "{% url 'account:register' %}";
            const home_url = "{% url 'website:home' %}"
    </script>
    <script type="text/javascript"  src="/static/js/saveJWT.js"></script>
  </head>

  <body>
    <div class="wrapper">
      <div class="title">Sign Up</div>
      <form id="submit-form">
        <div class="field">
          <input name="name" type="text" required />
          <label>Name</label>
        </div>
        <div class="field">
          <input name="email" type="text" required />
          <label>Email Address</label>
        </div>
        <div class="field">
          <input name="password" type="password" required />
          <label>Enter password</label>
        </div>
        <div class="field">
          <input name="password2" type="password" required />
          <label>Repeat password</label>
        </div>
        <div class="field">
          <input type="button" onclick="Submit(event)" value="Signup" />
        </div>
        <div class="signup-link">
          Already a member? <a href="{% url 'website:login' %}">Log in</a>
        </div>
      </form>
    </div>
  </body>
</html>