AI/urls.py
from django.urls import path
from .views import DiseaseDetectionCreationView, DetectionInformation, ListDetectionsForUser, ListDetectionModels

app_name = 'AI'

urlpatterns = [
    path('create', DiseaseDetectionCreationView.as_view(), name='create'),
    path('info', DetectionInformation.as_view()),
    path('list', ListDetectionsForUser.as_view()),
    path('models', ListDetectionModels.as_view(), name='models')
]

Auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/', include('account.urls')),
    path('detection/',include('AI.urls')),
    path('', include('website.urls')),
]

account/urls.py
from .views import UserRegisterationForm, UserLoginForm, UserProfileView, UserChangePasswordView, SendPasswordResetEmailView, UserPasswordResetView
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView

app_name = 'account'

urlpatterns = [
    path('register/', UserRegisterationForm.as_view(), name='register'),
    path('signin/', UserLoginForm.as_view(), name='signin'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('changepassword/', UserChangePasswordView.as_view(), name='changepassword'),
    path('forgotpassword/',SendPasswordResetEmailView.as_view(), name='forgotpassword' ),
    path('forgotpassword/<uid>/<token>', UserPasswordResetView.as_view()),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

website/urls.py
from django.urls import path
from .views import LoginView, HomeView, DetectionView, SignupView, AboutView

app_name = "website"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(),name='register'),
    path('', HomeView.as_view(), name='home'),
    path('detection/', DetectionView.as_view(),name='detection'),
    path('about/', AboutView.as_view(), name='about'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated

class LoginView(APIView):
    def get(self, request, format=None):
        return render(request, 'user/signin.html')

class SignupView(APIView):
    def get(self, request, format=None):
        return render(request, 'user/signup.html')
    

class HomeView(APIView): 
    def get(self, request, format=None):
        return render(request,'website/index.html')
    
class DetectionView(APIView):
    def get(self, request, format=None):
        return render(request,'website/detection.html')

class AboutView(APIView):
    def get(self, request, format=None):
        return render(request,'website/about.html')

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}{% endblock title %} | CropDiseaseDetector</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <script > 
        const loginUrl = "{% url 'website:login' %}";
        const tokenRefresh = "{% url 'account:token_refresh' %}";
    </script>
    <script type="text/javascript" src="/static/js/authorization.js"></script>
    {% block header %}
    
    {% endblock  %}
    
</head>

<body>
    <div class="navbar">
        <header class="navi">
            <nav>
                <ul class="nav__links">
                    <li class="navi"><a href="{%url 'website:home' %}" class="navi">Home</a></li>
                    <li class="navi"><a href="{%url 'website:detection' %}" class="navi">CropDiseaseAI</a></li>
                    <li class="navi"><a href="{%url 'website:about' %}" class="navi">About</a></li>
                </ul>
            </nav>
            <nav>
                <a class="cta" href="#"><button style="color: white;" class="navi">Profile</button></a>
                <!-- <a class="cta" href="#"><button
                        style="color: white;background-color: rgba(227, 3, 3, 0.997);" class="navi">Logout</button></a> -->
            </nav>
        </header>
    </div>
    
    {% block body %}
    
    {% endblock %}
</body>

</html>